### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hilaolu** [crarch/voj_web#1]
- Add friendly message in judging result
- Adapt variable test benches
- Navbar expand on default
- Modify waiting time for retireve judging result

**Comment by hilaolu** [comment]
- [ ] use icon replace 「通过」
- [ ] remember login status after refreshing
- [ ] foldable problem list
- [ ] wavedrom&image in markdown
- [ ] dynamicly update pass list on success submit
- [ ] (discussion needed) problem and editor seperate in different column?
- [ ] (discussion needed) way to convert md to html?
